pipeline {
    agent any

    environment {
    PARQUET_ROOT = "${env.WORKSPACE}/parquet_data"
        }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('PyTest DQ Framework') {
                    sh '''
                        python3 -m venv venv
                        ./venv/bin/pip install --upgrade pip
                        ./venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jenkins-postgres-credentials',
                    usernameVariable: 'DB_USER',
                    passwordVariable: 'DB_PASSWORD'
                )]) {
                    sh '''
                        cd PyTest DQ Framework
                        ./venv/bin/pytest tests \
                            -m parquet_data \
                            --db_host=postgres \
                            --db_port=5432 \
                            --db_name=mydatabase \
                            --db_user=$DB_USER \
                            --db_password=$DB_PASSWORD \
                            --parquet_root=$PARQUET_ROOT \
                            --html=html_report/report.html
                    '''
                }
            }
        }

        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/*.html', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
        failure {
            echo "Pipeline failed. Check the HTML report for details."
        }
    }
}
